# Generated by Django 3.2.4 on 2021-08-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dybanic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=20)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
