# Generated by Django 3.2.4 on 2021-08-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dybanic',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
